server: 
  port: 9999
#通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
eureka: 
  instance:
    hostname: server-a
  client: 
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://localhost:9998/eureka/