server: 
  port: 9090
  context-path: /shiro
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/manga?characterEncoding=utf-8
person: 
  name: 阿莉埃丝1
  age: 18
  name-age: kkkkDX
table-name: words