server: 
  port: 8778
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:9999/eureka/
spring: 
  application: 
    name: feign-client
feign: 
  hystrix: 
    enabled: true
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #缺省为1000  