server: 
  port: 6666
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:9999/eureka/
spring: 
  application: 
    name: ribbon->shana
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 30000 #缺省为1000  